import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Links from "../app/components/links";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        <Navbar />
        {children}
        <Links />


      </body>

    </html>
  );
}
